name: Docker Pipeline

on:
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: "Tag for the docker image."
        required: true
        default: "latest"

env:
  AWS_REGION: eu-central-1
  IMAGE_REGISTRY: public.ecr.aws/birdsonmars
  IMAGE_TAG: ${{ github.event.inputs.docker-image-tag }}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Validate Inputs
      run: |
        if [ -z "${{ github.event.inputs.docker-image-tag }}" ]; then
          echo "Error: 'docker-image-tag' input cannot be empty."
          exit 1
        fi
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/elio-deploy-role
        aws-region: eu-central-1

    - name: Build image
      run: |
        docker build -t ${{env.IMAGE_REGISTRY}}/elio:latest -f pipelines/Dockerfile.full .
        if [ "${{ github.event.inputs.docker-image-tag }}" != "latest" ]; then
          docker tag ${{env.IMAGE_REGISTRY}}/elio:latest ${{env.IMAGE_REGISTRY}}/elio:${{ env.IMAGE_TAG }}
        fi

    - name: Testing docker run
      run: |
        docker run --rm -v ./data:/app/data ${{env.IMAGE_REGISTRY}}/elio:latest \
          python scripts/run_pipeline.py --input-dir /app/data/MLI/input --output-dir /app/data/MLI/output --config-json '{"device": "cpu"}'

    - name: docker login to aws
      run: aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.IMAGE_REGISTRY }}
    - name: Push image
      run: |
        docker push ${{env.IMAGE_REGISTRY}}/elio:latest
        if [ "${{ github.event.inputs.docker-image-tag }}" != "latest" ]; then
          docker push ${{env.IMAGE_REGISTRY}}/elio:${{env.IMAGE_TAG}}
        fi
