name: Docker Pipeline

on:
  workflow_dispatch:
    inputs:
      docker-image-tag:
        description: "Tag for the docker image."
        required: true
        default: "latest"

# create variables
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  IMAGE_REGISTRY: public.ecr.aws/birdsonmars
  IMAGE_TAG: ${{ github.event.inputs.docker-image-tag }}

jobs:
  # unit-tests:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.10'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install --no-cache-dir \
  #           -r ./pipelines/requirements/segmentation.txt \
  #           -r ./pipelines/requirements/rotation.txt \
  #           -r ./pipelines/requirements/classifier.txt \
  #           -r ./pipelines/requirements/tesseract.txt \
  #           -r ./pipelines/requirements/empty_labels.txt \
  #           -r ./pipelines/requirements/postprocess.txt && \
  #           pip check
  #       pip install pytest
  #   # TODO
  #   # - name: Run tests
  #   #   run: |
  #   #     pytest unit_tests/

  build-docker-image:
    runs-on: ubuntu-latest
    # needs: unit-tests

    steps:
    - name: Validate Inputs
      run: |
        if [ -z "${{ github.event.inputs.docker-image-tag }}" ]; then
          echo "Error: 'docker-image-tag' input cannot be empty."
          exit 1
        fi
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Build image
      run: |
        docker build -t ${{env.IMAGE_REGISTRY}}/elio:latest -f pipelines/Dockerfile .
        if [ "${{ github.event.inputs.docker-image-tag }}" != "latest" ]; then
          docker tag ${{env.IMAGE_REGISTRY}}/elio:latest ${{env.IMAGE_REGISTRY}}/elio:${{ env.IMAGE_TAG }}
        fi

    # - name: Testing docker run
    #   run: |
    #     docker run --rm ${{env.IMAGE_REGISTRY}}/elio:latest \
    #       python scripts/run_pipeline.py --input-dir /app/data/MLI/input --output-dir /app/data/MLI/output --config-json '{"device": "cpu"}'

    - name: docker login to aws
      run: aws ecr-public get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.IMAGE_REGISTRY }}
    - name: Push image
      run: |
        docker push ${{env.IMAGE_REGISTRY}}/elio:latest
        if [ "${{ github.event.inputs.docker-image-tag }}" != "latest" ]; then
          docker push ${{env.IMAGE_REGISTRY}}/elio:${{env.IMAGE_TAG}}
        fi

    # - name: Create sif file

    # - name: Create Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     # This automatically generates the "What's Changed" notes
    #     generate_release_notes: true
    #     # If you built binaries in a previous step, list them here:
    #     # files: |
    #     #   dist/my-app.exe
    #     #   dist/my-app-macos
